"use client";

/**
 * Iconos de la aplicación (Lucide: trazo fino y coherente, el estándar de
 * las apps profesionales). Se piden por nombre para no depender del paquete
 * en cada pantalla y poder cambiarlos en un solo sitio.
 */
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  BadgeCheck,
  BookMarked,
  BookOpen,
  Brain,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheckBig,
  Clock,
  CloudUpload,
  Download,
  EllipsisVertical,
  Eye,
  FileText,
  Flame,
  Folder,
  GraduationCap,
  Headphones,
  House,
  Info,
  Layers,
  LayoutGrid,
  LibraryBig,
  Lightbulb,
  ListChecks,
  ListTree,
  Lock,
  LogOut,
  Mail,
  Maximize2,
  Minimize2,
  Moon,
  NotebookPen,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  Quote,
  RefreshCw,
  RotateCcw,
  RotateCw,
  ScanText,
  Search,
  Settings,
  ShieldCheck,
  Sigma,
  SkipBack,
  SkipForward,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Upload,
  User,
  Volume2,
  WandSparkles,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  home: House,
  library: LibraryBig,
  upload: Upload,
  cloudUpload: CloudUpload,
  settings: Settings,
  play: Play,
  pause: Pause,
  back10: RotateCcw,
  forward10: RotateCw,
  prev: SkipBack,
  next: SkipForward,
  search: Search,
  plus: Plus,
  trash: Trash2,
  sparkles: Sparkles,
  book: BookOpen,
  bookMarked: BookMarked,
  brain: ListTree,
  outline: ListTree,
  mind: Brain,
  headphones: Headphones,
  file: FileText,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  close: X,
  sun: Sun,
  moon: Moon,
  check: Check,
  checkCircle: CircleCheckBig,
  refresh: RefreshCw,
  warning: TriangleAlert,
  logout: LogOut,
  expand: Maximize2,
  collapse: Minimize2,
  clock: Clock,
  timer: Timer,
  folder: Folder,
  flame: Flame,
  wand: WandSparkles,
  download: Download,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  sort: ArrowUpDown,
  target: Target,
  trophy: Trophy,
  zap: Zap,
  graduation: GraduationCap,
  calendar: CalendarDays,
  lightbulb: Lightbulb,
  info: Info,
  shield: ShieldCheck,
  badge: BadgeCheck,
  phone: Smartphone,
  lock: Lock,
  mail: Mail,
  user: User,
  layers: Layers,
  grid: LayoutGrid,
  star: Star,
  sigma: Sigma,
  quote: Quote,
  pencil: Pencil,
  eye: Eye,
  scan: ScanText,
  trending: TrendingUp,
  more: EllipsisVertical,
  palette: Palette,
  volume: Volume2,
  notebook: NotebookPen,
  checklist: ListChecks,
};

export function Icon({
  name,
  size = 20,
  className,
  strokeWidth = 1.8,
}: {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const Componente = ICONS[name];
  if (!Componente) return null;
  // El play y la pausa, rellenos: se reconocen mejor de un vistazo.
  const relleno = name === "play" || name === "pause";
  return (
    <Componente
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      aria-hidden="true"
      fill={relleno ? "currentColor" : "none"}
    />
  );
}
